services:
  gas-station.api:
    container_name: gas-station.api
    image: ${DOCKER_REGISTRY}/gas-station.api
    restart: no
    build:
      context: .
      dockerfile: src/API/Dockerfile
      args:
        - BUILD_CONFIGURATION=Release
        - DOTNET_VERSION=8.0
    env_file:
      - .env
    volumes:
      - ${USERPROFILE}\.aspnet\https:/root/.aspnet/https:ro
    depends_on:
      gas-station.db:
        condition: service_healthy
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:8082;http://+:8080
      - ASPNETCORE_HTTPS_PORTS=8082
      - ASPNETCORE_HTTP_PORTS=8080
    ports:
      - "8081:8081"
      - "8080:8080"
      - "8082:8082"
      
  gas-station.db:
    image: postgres:17.1
    container_name: gas-station.db
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -h localhost -U ${POSTGRES_USER} -d ${POSTGRES_DB}'" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata:

networks:
  default:
    name: gs_default
    driver: bridge