<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <PreserveCompilationContext>true</PreserveCompilationContext>
  </PropertyGroup>
  
  <ItemGroup>
    <ProjectReference Include="..\Domain\Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentResults" Version="3.16.0" />
    <PackageReference Include="MediatR" Version="12.4.0" />
    <PackageReference Include="Riok.Mapperly" Version="4.0.0" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Purchases\Commands\" />
    <Folder Include="Purchases\DTOs\" />
  </ItemGroup>
  
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
